[server]
port = 8880

[request]
userAgent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"

[security]
enable = false
key = "qwertyuiopasdfghjklzxcvbnm"
